import { toNormalized } from "../../name-mappers";

export const assassin_elites = [
  "Dark Apostasy",
  "Locust's Fury",
  "Palm Strike",
  "Seeping Wound",
  "Shadow Theft",
  "Shattering Assault",
  "Way of the Assassin",
  "Flashing Blades",
  "Fox's Promise",
  "Golden Skull Strike",
  "Moebius Strike",
  "Temple Strike",
  "Assassin's Promise",
  "Mark of Insecurity",
  "Shadow Prison",
  "Shroud of Silence",
  "Siphon Strength",
  "Way of the Empty Palm",
  "Beguiling Haze",
  "Hidden Caltrops",
  "Shadow Form",
  "Shadow Form (PvP)",
  "Shadow Shroud",
  "Assault Enchantments",
  "Aura of Displacement",
  "Shadow Meld",
  "Wastrel's Collapse",
].map(toNormalized);
