import { toNormalized } from "../../name-mappers";

export const elementalist_elites = [
  "Blinding Surge",
  "Glimmering Mark",
  "Gust",
  "Invoke Lightning",
  "Lightning Surge",
  "Mind Shock",
  "Mind Shock (PvP)",
  "Ride the Lightning",
  "Ride the Lightning (PvP)",
  "Thunderclap",
  "Obsidian Flesh",
  "Sandstorm",
  "Shockwave",
  "Stone Sheath",
  "Unsteady Ground",
  "Elemental Attunement",
  "Energy Boon",
  "Ether Prism",
  "Ether Prodigy",
  "Ether Renewal",
  "Ether Renewal (PvP)",
  "Glyph of Energy",
  "Master of Magic",
  "Over the Limit",
  "Double Dragon",
  "Mind Blast",
  "Mind Burn",
  "Savannah Heat",
  "Savannah Heat (PvP)",
  "Searing Flames",
  "Star Burst",
  "Icy Shackles",
  "Mind Freeze",
  "Mind Freeze (PvP)",
  "Mirror of Ice",
  "Mist Form",
  "Mist Form (PvP)",
  "Shatterstone",
  "Ward Against Harm",
  "Ward Against Harm (PvP)",
  "Water Trident",
  "Glyph of Renewal",
  "Second Wind",
].map(toNormalized);
