import { toNormalized } from "../../name-mappers";

export const mesmer_elites = [
  "Enchanter's Conundrum",
  "Enchanter's Conundrum (PvP)",
  "Energy Surge",
  "Hex Eater Vortex",
  "Panic",
  "Power Block",
  "Power Flux",
  "Psychic Distraction",
  "Simple Thievery",
  "Visions of Regret",
  "Visions of Regret (PvP)",
  "Arcane Languor",
  "Keystone Signet",
  "Mantra of Recovery",
  "Psychic Instability",
  "Psychic Instability (PvP)",
  "Stolen Speed",
  "Stolen Speed (PvP)",
  "Symbols of Inspiration",
  "Time Ward",
  "Air of Disenchantment",
  "Crippling Anguish",
  "Crippling Anguish (PvP)",
  "Fevered Dreams",
  "Fevered Dreams (PvP)",
  "Illusionary Weaponry",
  "Illusionary Weaponry (PvP)",
  "Ineptitude",
  "Migraine",
  "Migraine (PvP)",
  "Recurring Insecurity",
  "Shared Burden",
  "Shared Burden (PvP)",
  "Signet of Illusions",
  "Energy Drain",
  "Extend Conditions",
  "Lyssa's Aura",
  "Mantra of Recall",
  "Power Leech",
  "Tease",
  "Echo",
  "Expel Hexes",
  "Shatter Storm",
  "Signet of Midnight",
].map(toNormalized);
