import { toNormalized } from "../../name-mappers";

export const monk_elites = [
  "Blessed Light",
  "Boon Signet",
  "Healer's Boon",
  "Judgment Strike",
  "Peace and Harmony",
  "Scribe's Insight",
  "Spell Breaker",
  "Unyielding Aura",
  "Unyielding Aura (PvP)",
  "Withdraw Hexes",
  "Glimmer of Light",
  "Healer's Covenant",
  "Healing Burst",
  "Healing Hands",
  "Healing Light",
  "Light of Deliverance",
  "Light of Deliverance (PvP)",
  "Word of Healing",
  "Air of Enchantment",
  "Amity",
  "Aura of Faith",
  "Divert Hexes",
  "Life Barrier",
  "Life Sheath",
  "Mark of Protection",
  "Restore Condition",
  "Shield of Deflection",
  "Shield of Regeneration",
  "Zealous Benediction",
  "Balthazar's Pendulum",
  "Defender's Zeal",
  "Ray of Judgment",
  "Shield of Judgment",
  "Signet of Judgment",
  "Signet of Judgment (PvP)",
  "Word of Censure",
  "Empathic Removal",
  "Martyr",
  "Signet of Removal",
].map(toNormalized);
