import { toNormalized } from "../../name-mappers";

export const necromancer_elites = [
  "Blood is Power",
  "Cultist's Fervor",
  "Life Transfer",
  "Offering of Blood",
  "Order of the Vampire",
  "Ravenous Gaze",
  "Signet of Suffering",
  "Soul Leech",
  "Spoil Victor",
  "Spoil Victor (PvP)",
  "Vampiric Spirit",
  "Well of Power",
  "Corrupt Enchantment",
  "Depravity",
  "Feast of Corruption",
  "Lingering Curse",
  "Order of Apostasy",
  "Pain of Disenchantment",
  "Plague Signet",
  "Soul Bind",
  "Spiteful Spirit",
  "Weaken Knees",
  "Wither",
  "Animate Flesh Golem",
  "Aura of the Lich",
  "Contagion",
  "Discord",
  "Discord (PvP)",
  "Jagged Bones",
  "Order of Undeath",
  "Tainted Flesh",
  "Toxic Chill",
  "Virulence",
  "Icy Veins",
  "Reaper's Mark",
  "Soul Taker",
  "Wail of Doom",
  "Grenth's Balance",
].map(toNormalized);
