import { toNormalized } from "../../name-mappers";

export const ranger_elites = [
  "Enraged Lunge",
  "Enraged Lunge (PvP)",
  "Ferocious Strike",
  "Heal as One",
  "Heal as One (PvP)",
  "Lacerate",
  "Rampage as One",
  "Strike as One",
  '"Together as One!"',
  "Archer's Signet",
  "Escape",
  "Escape (PvP)",
  "Expert's Dexterity",
  "Expert's Dexterity (PvP)",
  "Glass Arrows",
  "Glass Arrows (PvP)",
  "Infuriating Heat",
  "Marksman's Wager",
  "Oath Shot",
  "Practiced Stance",
  "Trapper's Focus",
  "Barrage",
  "Broad Head Arrow",
  "Burning Arrow",
  "Crippling Shot",
  "Melandru's Shot",
  "Prepared Shot",
  "Punishing Shot",
  "Equinox",
  "Famine",
  "Greater Conflagration",
  "Incendiary Arrows",
  "Melandru's Arrows",
  "Melandru's Resilience",
  "Poison Arrow",
  "Quicksand",
  "Scavenger's Focus",
  "Smoke Trap",
  "Spike Trap",
  "Magebane Shot",
  "Quick Shot",
].map(toNormalized);
