import { toNormalized } from "../../name-mappers";

export const ritualist_elites = [
  "Caretaker's Charge",
  "Clamor of Souls",
  "Destructive Was Glaive",
  "Destructive Was Glaive (PvP)",
  "Grasping Was Kuurong",
  "Offering of Spirit",
  "Offering of Spirit (Togo)",
  "Signet of Spirits",
  "Signet of Spirits (PvP)",
  "Weapon of Fury",
  "Signet of Ghostly Might",
  "Signet of Ghostly Might (PvP)",
  "Wanderlust",
  "Wanderlust (PvP)",
  "Weapon of Quickening",
  "Defiant Was Xinrae",
  "Preservation",
  "Preservation (PvP)",
  "Spirit Light Weapon",
  "Tranquil Was Tanasen",
  "Vengeful Was Khanhei",
  "Weapon of Remedy",
  "Xinrae's Weapon",
  "Attuned Was Songkai",
  "Consume Soul",
  "Reclaim Essence",
  "Ritual Lord",
  "Soul Twisting",
  "Spirit Channeling",
  "Spirit's Strength",
  "Weapons of Three Forges",
  "Wielder's Zeal",
].map(toNormalized);
