import { toNormalized } from "../../name-mappers";

export const warrior_elites = [
  "Cleave",
  "Decapitate",
  "Eviscerate",
  "Triple Chop",
  "Whirling Axe",
  "Backbreaker",
  "Devastating Hammer",
  "Earth Shaker",
  "Enraged Smash",
  "Enraged Smash (PvP)",
  "Forceful Blow",
  "Magehunter's Smash",
  "Battle Rage",
  "Bull's Charge",
  "Charging Strike",
  "Defy Pain",
  "Defy Pain (PvP)",
  "Dwarven Battle Stance",
  "Flourish",
  "Headbutt",
  "Magehunter Strike",
  "Primal Rage",
  "Rage of the Ntouka",
  "Seven Weapons Stance",
  "Warrior's Endurance",
  "Warrior's Endurance (PvP)",
  "Crippling Slash",
  "Dragon Slash",
  "Dragon Slash (Turai Ossa)",
  "Hundred Blades",
  "Quivering Blade",
  '"Charge!"',
  '"Victory Is Mine!"',
  "Auspicious Parry",
  "Gladiator's Defense",
  "Shove",
  "Soldier's Stance",
  "Soldier's Stance (PvP)",
  "Steady Stance",
  '"Coward!"',
  '"You\'re All Alone!"',
  "Skull Crack",
].map(toNormalized);
