import { toNormalized } from "../../name-mappers";

export const factions_skills = new Set(
  [
    '"Coward!"',
    '"None Shall Pass!"',
    '"On Your Knees!"',
    '"Retreat!"',
    '"Save Yourselves!"',
    '"You Will Die!"',
    "Auspicious Blow",
    "Auspicious Parry",
    "Dragon Slash",
    "Drunken Blow",
    "Enraged Smash",
    "Enraged Smash (PvP)",
    "Fierce Blow",
    "Forceful Blow",
    "Furious Axe",
    "Jaizhenju Strike",
    "Lacerating Chop",
    "Leviathan's Sweep",
    "Penetrating Chop",
    "Penetrating Chop",
    "Primal Rage",
    "Protector's Defense",
    "Quivering Blade",
    "Renewing Smash",
    "Renewing Smash (PvP)",
    "Shove",
    "Signet of Strength",
    "Silverwing Slash",
    "Standing Slash",
    "Sun and Moon Slash",
    "Tiger Stance",
    "Triple Chop",
    "Whirling Axe",
    "Yeti Smash",
    "Archer's Signet",
    "Bestial Fury",
    "Bestial Mauling",
    "Brambles",
    "Broad Head Arrow",
    "Conflagration",
    "Enraged Lunge",
    "Enraged Lunge (PvP)",
    "Equinox",
    "Famine",
    "Focused Shot",
    "Glass Arrows",
    "Glass Arrows (PvP)",
    "Heal as One",
    "Heal as One (PvP)",
    "Lacerate",
    "Marauder's Shot",
    "Melandru's Shot",
    "Needling Shot",
    "Poisonous Bite",
    "Pounce",
    "Predatory Bond",
    "Predatory Bond (PvP)",
    "Run as One",
    "Savage Pounce",
    "Seeking Arrows",
    "Snare",
    "Splinter Shot",
    "Sundering Attack",
    "Sundering Attack (PvP)",
    "Tranquility",
    "Trapper's Focus",
    "Triple Shot",
    "Viper's Nest",
    "Zojun's Haste",
    "Zojun's Shot",
    "Air of Enchantment",
    "Blessed Light",
    "Boon Signet",
    "Deny Hexes",
    "Dwayna's Sorrow",
    "Empathic Removal",
    "Ethereal Light",
    "Extinguish",
    "Gift of Health",
    "Healing Burst",
    "Healing Light",
    "Healing Whisper",
    "Heaven's Delight",
    "Jamei's Gaze",
    "Karei's Healing Circle",
    "Kirin's Wrath",
    "Life Sheath",
    "Ray of Judgment",
    "Release Enchantments",
    "Resurrection Chant",
    "Reverse Hex",
    "Selfless Spirit",
    "Shield Guardian",
    "Signet of Rage",
    "Signet of Rejuvenation",
    "Spear of Light",
    "Spell Shield",
    "Spirit Bond",
    "Spirit Bond (PvP)",
    "Stonesoul Strike",
    "Withdraw Hexes",
    "Word of Censure",
    "Sacrifice",
    "Animate Flesh Golem",
    "Animate Vampiric Horror",
    "Bitter Chill",
    "Blood Bond",
    "Blood Drinker",
    "Cultist's Fervor",
    "Defile Enchantments",
    "Discord",
    "Discord (PvP)",
    "Enfeebling Touch",
    "Fetid Ground",
    "Gaze of Contempt",
    "Icy Veins",
    "Jaundiced Gaze",
    "Lifebane Strike",
    "Oppressive Gaze",
    "Order of Apostasy",
    "Reckless Haste",
    "Rising Bile",
    "Shivers of Dread",
    "Signet of Corruption",
    "Soul Bind",
    "Spoil Victor",
    "Spoil Victor (PvP)",
    "Taste of Pain",
    "Vampiric Bite",
    "Vampiric Spirit",
    "Vampiric Swarm",
    "Vile Miasma",
    "Wail of Doom",
    "Sacrifice",
    "Wallow's Bite",
    "Sacrifice",
    "Weaken Knees",
    "Well of Weariness",
    "Accumulated Pain",
    "Accumulated Pain (PvP)",
    "Ancestor's Visage",
    "Arcane Languor",
    "Arcane Larceny",
    "Auspicious Incantation",
    "Complicate",
    "Conjure Nightmare",
    "Ether Nightmare",
    "Ether Signet",
    "Expel Hexes",
    "Feedback",
    "Hex Eater Signet",
    "Illusion of Pain",
    "Illusion of Pain (PvP)",
    "Images of Remorse",
    "Kitah's Burden",
    "Lyssa's Aura",
    "Lyssa's Balance",
    "Overload",
    "Power Leech",
    "Power Return",
    "Psychic Distraction",
    "Psychic Instability",
    "Psychic Instability (PvP)",
    "Recurring Insecurity",
    "Revealed Enchantment",
    "Revealed Hex",
    "Shared Burden",
    "Shared Burden (PvP)",
    "Shatter Storm",
    "Signet of Disenchantment",
    "Signet of Disruption",
    "Stolen Speed",
    "Stolen Speed (PvP)",
    "Unnatural Signet",
    "Unnatural Signet (PvP)",
    "Arc Lightning",
    "Ash Blast",
    "Bed of Coals",
    "Breath of Fire",
    "Burning Speed",
    "Churning Earth",
    "Double Dragon",
    "Dragon's Stomp",
    "Elemental Lord",
    "Energy Boon",
    "Glyph of Essence",
    "Gust",
    "Icy Prism",
    "Lava Arrows",
    "Lightning Hammer",
    "Lightning Hammer (PvP)",
    "Mirror of Ice",
    "Ride the Lightning",
    "Ride the Lightning (PvP)",
    "Second Wind",
    "Shatterstone",
    "Shock Arrow",
    "Shockwave",
    "Sliver Armor",
    "Smoldering Embers",
    "Star Burst",
    "Teinai's Crystals",
    "Teinai's Heat",
    "Teinai's Prison",
    "Teinai's Wind",
    "Unsteady Ground",
    "Vapor Blade",
    "Ward of Stability",
    "Upkeep",
    "Assassin's Promise",
    "Aura of Displacement",
    "Beguiling Haze",
    "Black Lotus Strike",
    "Black Mantis Thrust",
    "Blades of Steel",
    "Blinding Powder",
    "Caltrops",
    "Crippling Dagger",
    "Critical Defenses",
    "Critical Eye",
    "Critical Strike",
    "Dancing Daggers",
    "Dark Apostasy",
    "Dark Escape",
    "Dark Prison",
    "Dash",
    "Death Blossom",
    "Death Blossom (PvP)",
    "Death's Charge",
    "Desperate Strike",
    "Disrupting Stab",
    "Enduring Toxin",
    "Entangling Asp",
    "Exhausting Assault",
    "Expose Defenses",
    "Expunge Enchantments",
    "Falling Spider",
    "Flashing Blades",
    "Fox Fangs",
    "Fox Fangs (PvP)",
    "Golden Lotus Strike",
    "Golden Phoenix Strike",
    "Heart of Shadow",
    "Horns of the Ox",
    "Impale",
    "Iron Palm",
    "Jagged Strike",
    "Jungle Strike",
    "Leaping Mantis Sting",
    "Locust's Fury",
    "Mantis Touch",
    "Mark of Death",
    "Mark of Instability",
    "Mirrored Stance",
    "Moebius Strike",
    "Nine Tail Strike",
    "Palm Strike",
    "Recall",
    "Repeating Strike",
    "Return",
    "Scorpion Wire",
    "Seeping Wound",
    "Shadow Form",
    "Shadow Form (PvP)",
    "Shadow Refuge",
    "Shadow Sanctuary",
    "Shadow Shroud",
    "Shadow of Haste",
    "Shadowy Burden",
    "Shameful Fear",
    "Sharpen Daggers",
    "Shroud of Distress",
    "Shroud of Distress (PvP)",
    "Shroud of Silence",
    "Signet of Malice",
    "Signet of Shadows",
    "Siphon Speed",
    "Siphon Strength",
    "Spirit Walk",
    "Temple Strike",
    "Twisting Fangs",
    "Unseen Fury",
    "Unseen Fury (PvP)",
    "Unsuspecting Strike",
    "Viper's Defense",
    "Way of Perfection",
    "Way of the Empty Palm",
    "Way of the Fox",
    "Way of the Lotus",
    "Wild Strike",
    "Wild Strike (PvP)",
    "Sacrifice",
    "Ancestors' Rage",
    "Ancestors' Rage (PvP)",
    "Anguished Was Lingwah",
    "Armor of Unfeeling",
    "Armor of Unfeeling (PvP)",
    "Attuned Was Songkai",
    "Binding Chains",
    "Blind Was Mingson",
    "Bloodsong",
    "Bloodsong (PvP)",
    "Boon of Creation",
    "Brutal Weapon",
    "Channeled Strike",
    "Clamor of Souls",
    "Consume Soul",
    "Cruel Was Daoshen",
    "Defiant Was Xinrae",
    "Destruction",
    "Destruction (PvP)",
    "Disenchantment",
    "Disenchantment (PvP)",
    "Displacement",
    "Displacement (PvP)",
    "Dissonance",
    "Dissonance (PvP)",
    "Doom",
    "Draw Spirit",
    "Dulled Weapon",
    "Earthbind",
    "Earthbind (PvP)",
    "Essence Strike",
    "Explosive Growth",
    "Feast of Souls",
    "Flesh of My Flesh",
    "Flesh of My Flesh (PvP)",
    "Gaze from Beyond",
    "Generous Was Tsungrai",
    "Sacrifice",
    "Ghostly Haste",
    "Grasping Was Kuurong",
    "Guided Weapon",
    "Lamentation",
    "Life",
    "Life (PvP)",
    "Lively Was Naomei",
    "Mend Body and Soul",
    "Mighty Was Vorizun",
    "Nightmare Weapon",
    "Pain",
    "Pain (PvP)",
    "Painful Bond",
    "Preservation",
    "Preservation (PvP)",
    "Protective Was Kaolai",
    "Recuperation",
    "Recuperation (PvP)",
    "Resilient Was Xiko",
    "Resilient Weapon",
    "Restoration",
    "Restoration (PvP)",
    "Ritual Lord",
    "Sacrifice",
    "Rupture Soul",
    "Shadowsong",
    "Shadowsong (PvP)",
    "Shelter",
    "Shelter (PvP)",
    "Signet of Creation",
    "Signet of Spirits",
    "Signet of Spirits (PvP)",
    "Soothing",
    "Soothing (PvP)",
    "Soothing Memories",
    "Soul Twisting",
    "Spirit Boon Strike",
    "Spirit Burn",
    "Spirit Channeling",
    "Spirit Light",
    "Sacrifice",
    "Spirit Light Weapon",
    "Spirit Rift",
    "Spirit Siphon",
    "Spirit Transfer",
    "Spirit to Flesh",
    "Splinter Weapon",
    "Splinter Weapon (PvP)",
    "Summon Spirits",
    "Tranquil Was Tanasen",
    "Union",
    "Union (PvP)",
    "Vengeful Was Khanhei",
    "Vengeful Weapon",
    "Vital Weapon",
    "Wailing Weapon",
    "Wanderlust",
    "Wanderlust (PvP)",
    "Weapon of Quickening",
    "Weapon of Shadow",
    "Weapon of Warding",
    "Weapon of Warding (PvP)",
    "Wielder's Boon",
    "Spear of Fury",
    "Aura of Holy Might",
  ].map(toNormalized)
);
