import { toNormalized } from "../../name-mappers";

export const gwen_skills = new Set(
  [
    '"I Meant to Do That!"',
    "Body Blow",
    "Disarm",
    "Distracting Strike",
    "Grapple",
    "Keen Chop",
    "Knee Cutter",
    "Pulverizing Smash",
    "Soldier's Speed",
    "Symbolic Strike",
    "Body Shot",
    "Companionship",
    "Disrupting Shot",
    "Expert Focus",
    "Feral Aggression",
    "Piercing Trap",
    "Poison Tip Signet",
    "Rapid Fire",
    "Sloth Hunter's Shot",
    "Sloth Hunter's Shot (PvP)",
    "Volley",
    "Upkeep",
    "Aura of Stability",
    "Castigation Signet",
    "Cure Hex",
    "Healing Ribbon",
    "Patient Spirit",
    "Purifying Veil",
    "Smite Condition",
    "Smiter's Boon",
    "Smiter's Boon (PvP)",
    "Spotless Mind",
    "Spotless Soul",
    "Angorodon's Gaze",
    "Atrophy",
    "Cacophony",
    "Defile Defenses",
    "Foul Feast",
    "Hexer's Vigor",
    "Masochism",
    "Masochism (PvP)",
    "Putrid Bile",
    "Well of Ruin",
    "Withering Aura",
    "Aneurysm",
    "Calculated Risk",
    "Calculated Risk (PvP)",
    "Confusing Images",
    "Power Lock",
    "Shrinking Armor",
    "Signet of Distraction",
    "Signet of Recall",
    "Sum of All Fears",
    "Wandering Eye",
    "Wandering Eye (PvP)",
    "Waste Not, Want Not",
    "Earthen Shackles",
    "Energy Blast",
    "Glowing Ice",
    "Glyph of Immolation",
    "Glyph of Swiftness",
    "Magnetic Surge",
    "Shell Shock",
    "Slippery Ground",
    "Slippery Ground (PvP)",
    "Ward of Weakness",
    "Winter's Embrace",
    "Falling Lotus Strike",
    "Golden Fang Strike",
    "Lotus Strike",
    "Sadist's Signet",
    "Shadow Fang",
    "Signet of Deadly Corruption",
    "Signet of Deadly Corruption (PvP)",
    "Smoke Powder Defense",
    "Trampling Ox",
    "Vampiric Assault",
    "Way of the Master",
    "Agony",
    "Agony (PvP)",
    "Energetic Was Lee Sa",
    "Ghostly Weapon",
    "Mending Grip",
    "Pure Was Li Ming",
    "Rejuvenation",
    "Rejuvenation (PvP)",
    "Spiritleech Aura",
    "Sundering Weapon",
    "Weapon of Aggression",
    "Weapon of Renewal",
    "Anthem of Disruption",
    "Anthem of Disruption (PvP)",
    "Anthem of Weariness",
    "Burning Shield",
    "Chest Thumper",
    "Hasty Refrain",
    "Holy Spear",
    "Inspirational Speech",
    "Maiming Spear",
    "Spear Swipe",
    "Spear of Redemption",
    "Aura Slicer",
    "Crippling Victory",
    "Farmer's Scythe",
    "Grenth's Aura",
    "Pious Fury",
    "Pious Fury (PvP)",
    "Radiant Scythe",
    "Shield of Force",
    "Signet of Mystic Speed",
    "Signet of Pious Restraint",
    "Signet of Pious Restraint (PvP)",
    "Zealous Sweep",
    '"By Ural\'s Hammer!"',
    '"Dodge This!"',
    '"Don\'t Trip!"',
    '"Finish Him!"',
    '"I Am Unstoppable!"',
    '"I Am the Strongest!"',
    '"You Are All Weaklings!"',
    '"You Move Like a Dwarf!"',
    "A Touch of Guile",
    "Air of Superiority",
    "Alkar's Alchemical Acid",
    "Asuran Scan",
    "Black Powder Mine",
    "Brawling Headbutt",
    "Breath of the Great Dwarf",
    "Club of a Thousand Bears",
    "Deft Strike",
    "Drunken Master",
    "Dwarven Stability",
    "Ear Bite",
    "Ebon Battle Standard of Courage",
    "Ebon Battle Standard of Honor",
    "Ebon Battle Standard of Wisdom",
    "Ebon Escape",
    "Ebon Vanguard Assassin Support",
    "Ebon Vanguard Sniper Support",
    "Feel No Pain",
    "Great Dwarf Armor",
    "Great Dwarf Weapon",
    "Light of Deldrimor",
    "Low Blow",
    "Mental Block",
    "Mindbender",
    "Pain Inverter",
    "Radiation Field",
    "Raven Blessing",
    "Signet of Infection",
    "Smooth Criminal",
    "Sneak Attack",
    "Snow Storm",
    "Summon Ice Imp",
    "Summon Mursaat",
    "Summon Naga Shaman",
    "Summon Ruby Djinn",
    "Technobabble",
    "Tryptophan Signet",
    "Ursan Blessing",
    "Volfen Blessing",
    "Weakness Trap",
    "Winds",
    "Any",
  ].map(toNormalized)
);
