import { toNormalized } from "../../name-mappers";

export const nightfall_skills = new Set(
  [
    '"You\'re All Alone!"',
    "Agonizing Chop",
    "Barbarous Slice",
    "Burst of Aggression",
    "Charging Strike",
    "Counterattack",
    "Crippling Slash",
    "Critical Chop",
    "Decapitate",
    "Enraging Charge",
    "Flail",
    "Frenzied Defense",
    "Headbutt",
    "Lion's Comfort",
    "Magehunter Strike",
    "Magehunter's Smash",
    "Mokele Smash",
    "Overbearing Smash",
    "Rage of the Ntouka",
    "Signet of Stamina",
    "Soldier's Defense",
    "Soldier's Stance",
    "Soldier's Stance (PvP)",
    "Soldier's Strike",
    "Steady Stance",
    "Steelfang Slash",
    "Whirlwind Attack",
    "Arcing Shot",
    "Barbed Arrows",
    "Burning Arrow",
    "Crossfire",
    "Disrupting Accuracy",
    "Expert's Dexterity",
    "Expert's Dexterity (PvP)",
    "Forked Arrow",
    "Heket's Rampage",
    "Infuriating Heat",
    "Keen Arrow",
    "Keen Arrow (PvP)",
    "Magebane Shot",
    "Natural Stride",
    "Never Rampage Alone",
    "Pestilence",
    "Prepared Shot",
    "Quicksand",
    "Rampage as One",
    "Roaring Winds",
    "Scavenger's Focus",
    "Screaming Shot",
    "Smoke Trap",
    "Storm's Embrace",
    "Strike as One",
    "Toxicity",
    "Trapper's Speed",
    "Tripwire",
    "Upkeep",
    "Balthazar's Pendulum",
    "Defender's Zeal",
    "Dismiss Condition",
    "Divert Hexes",
    "Glimmer of Light",
    "Healer's Boon",
    "Healer's Covenant",
    "Healing Ring",
    "Holy Haste",
    "Judge's Intervention",
    "Light of Deliverance",
    "Light of Deliverance (PvP)",
    "Mending Touch",
    "Pensive Guardian",
    "Renew Life",
    "Restful Breeze",
    "Reversal of Damage",
    "Scourge Enchantment",
    "Scribe's Insight",
    "Seed of Life",
    "Shield of Absorption",
    "Signet of Mystic Wrath",
    "Signet of Removal",
    "Supportive Spirit",
    "Watchful Healing",
    "Words of Comfort",
    "Zealous Benediction",
    "Sacrifice",
    "Animate Shambling Horror",
    "Blood of the Aggressor",
    "Contagion",
    "Corrupt Enchantment",
    "Depravity",
    "Envenom Enchantments",
    "Feast for the Dead",
    "Jagged Bones",
    "Mark of Fury",
    "Meekness",
    "Sacrifice",
    "Necrosis",
    "Order of Undeath",
    "Pain of Disenchantment",
    "Poisoned Heart",
    "Putrid Flesh",
    "Ravenous Gaze",
    "Sacrifice",
    "Reaper's Mark",
    "Rip Enchantment",
    "Signet of Lost Souls",
    "Signet of Sorrow",
    "Signet of Suffering",
    "Toxic Chill",
    "Ulcerous Lungs",
    "Vocal Minority",
    "Well of Darkness",
    "Well of Silence",
    "Air of Disenchantment",
    "Cry of Pain",
    "Discharge Enchantment",
    "Drain Delusions",
    "Enchanter's Conundrum",
    "Enchanter's Conundrum (PvP)",
    "Ether Phantom",
    "Extend Conditions",
    "Frustration",
    "Frustration (PvP)",
    "Hex Eater Vortex",
    "Hypochondria",
    "Mirror of Disenchantment",
    "Mirror of Disenchantment (PvP)",
    "Mistrust",
    "Mistrust (PvP)",
    "Persistence of Memory",
    "Power Flux",
    "Price of Pride",
    "Signet of Clumsiness",
    "Signet of Clumsiness (PvP)",
    "Signet of Illusions",
    "Simple Thievery",
    "Spiritual Pain",
    "Spiritual Pain (PvP)",
    "Symbolic Celerity",
    "Symbolic Posture",
    "Symbols of Inspiration",
    "Tease",
    "Visions of Regret",
    "Visions of Regret (PvP)",
    "Wastrel's Demise",
    "Web of Disruption",
    "Web of Disruption (PvP)",
    "Blinding Surge",
    "Chilling Winds",
    "Ebon Hawk",
    "Elemental Flame",
    "Elemental Flame (PvP)",
    "Ether Prism",
    "Flame Djinn's Haste",
    "Freezing Gust",
    "Frigid Armor",
    "Glowing Gaze",
    "Glowstone",
    "Glyph of Restoration",
    "Icy Shackles",
    "Intensity",
    "Invoke Lightning",
    "Lightning Bolt",
    "Liquid Flame",
    "Master of Magic",
    "Mind Blast",
    "Sandstorm",
    "Savannah Heat",
    "Savannah Heat (PvP)",
    "Searing Flames",
    "Steam",
    "Stone Sheath",
    "Stone Striker",
    "Stoneflesh Aura",
    "Storm Djinn's Haste",
    "Upkeep",
    "Assassin's Remedy",
    "Assassin's Remedy (PvP)",
    "Assault Enchantments",
    "Augury of Death",
    "Black Spider Strike",
    "Critical Agility",
    "Deadly Haste",
    "Deadly Paradox",
    "Death's Retreat",
    "Disrupting Dagger",
    "Feigned Neutrality",
    "Fox's Promise",
    "Golden Fox Strike",
    "Golden Skull Strike",
    "Hidden Caltrops",
    "Lift Enchantment",
    "Malicious Strike",
    "Mark of Insecurity",
    "Shadow Meld",
    "Shadow Prison",
    "Shadow Walk",
    "Shattering Assault",
    "Signet of Toxic Shock",
    "Signet of Twilight",
    "Swap",
    "Wastrel's Collapse",
    "Way of the Assassin",
    "Sacrifice",
    "Anguish",
    "Anguish (PvP)",
    "Caretaker's Charge",
    "Death Pact Signet",
    "Death Pact Signet (PvP)",
    "Destructive Was Glaive",
    "Destructive Was Glaive (PvP)",
    "Empowerment",
    "Empowerment (PvP)",
    "Gaze of Fury",
    "Gaze of Fury (PvP)",
    "Ghostmirror Light",
    "Offering of Spirit",
    "Sacrifice",
    "Reclaim Essence",
    "Recovery",
    "Recovery (PvP)",
    "Renewing Memories",
    "Renewing Surge",
    "Sight Beyond Sight",
    "Signet of Binding",
    "Signet of Ghostly Might",
    "Signet of Ghostly Might (PvP)",
    "Spirit's Gift",
    "Spirit's Strength",
    "Vampirism",
    "Vocal Was Sogolon",
    "Warmonger's Weapon",
    "Weapon of Fury",
    "Weapon of Remedy",
    "Wielder's Remedy",
    "Wielder's Strike",
    "Wielder's Zeal",
    "Xinrae's Weapon",
    '"Brace Yourself!"',
    '"Brace Yourself!" (PvP)',
    '"Can\'t Touch This!"',
    '"Can\'t Touch This!" (PvP)',
    '"Fall Back!"',
    '"Fall Back!" (PvP)',
    '"Find Their Weakness!"',
    '"Find Their Weakness!" (PvP)',
    '"Go for the Eyes!"',
    '"Go for the Eyes!" (PvP)',
    '"Help Me!"',
    '"Help Me!" (PvP)',
    '"Incoming!"',
    '"Incoming!" (PvP)',
    '"It\'s Just a Flesh Wound."',
    '"Lead the Way!"',
    '"Make Haste!"',
    '"Make Your Time!"',
    '"Never Give Up!"',
    '"Never Give Up!" (PvP)',
    '"Never Surrender!"',
    '"Never Surrender!" (PvP)',
    '"Stand Your Ground!"',
    '"Stand Your Ground!" (PvP)',
    '"The Power Is Yours!"',
    '"There\'s Nothing to Fear!"',
    '"They\'re on Fire!"',
    '"We Shall Return!"',
    '"We Shall Return!" (PvP)',
    "Aggressive Refrain",
    "Angelic Bond",
    "Angelic Protection",
    "Anthem of Envy",
    "Anthem of Envy (PvP)",
    "Anthem of Flame",
    "Anthem of Fury",
    "Anthem of Guidance",
    "Aria of Restoration",
    "Aria of Zeal",
    "Awe",
    "Ballad of Restoration",
    "Ballad of Restoration (PvP)",
    "Barbed Spear",
    "Bladeturn Refrain",
    "Bladeturn Refrain (PvP)",
    "Blazing Finale",
    "Blazing Finale (PvP)",
    "Blazing Spear",
    "Burning Refrain",
    "Cautery Signet",
    "Chorus of Restoration",
    "Crippling Anthem",
    "Cruel Spear",
    "Defensive Anthem",
    "Defensive Anthem (PvP)",
    "Disrupting Throw",
    "Enduring Harmony",
    "Energizing Chorus",
    "Energizing Finale",
    "Finale of Restoration",
    "Finale of Restoration (PvP)",
    "Focused Anger",
    "Glowing Signet",
    "Godspeed",
    "Harrier's Toss",
    "Harrier's Toss (PvP)",
    "Hexbreaker Aria",
    "Leader's Comfort",
    "Leader's Zeal",
    "Lyric of Purification",
    "Lyric of Zeal",
    "Mending Refrain",
    "Mending Refrain (PvP)",
    "Merciless Spear",
    "Mighty Throw",
    "Natural Temper",
    "Purifying Finale",
    "Remedy Signet",
    "Signet of Aggression",
    "Signet of Return",
    "Signet of Return (PvP)",
    "Signet of Synergy",
    "Slayer's Spear",
    "Soldier's Fury",
    "Song of Concentration",
    "Song of Power",
    "Song of Purification",
    "Song of Restoration",
    "Song of Restoration (PvP)",
    "Spear of Lightning",
    "Stunning Strike",
    "Swift Javelin",
    "Unblockable Throw",
    "Vicious Attack",
    "Wearying Spear",
    "Wild Throw",
    "Zealous Anthem",
    "Arcane Zeal",
    "Armor of Sanctity",
    "Attacker's Insight",
    "Aura of Thorns",
    "Aura of Thorns (PvP)",
    "Avatar of Balthazar",
    "Avatar of Dwayna",
    "Avatar of Dwayna (PvP)",
    "Avatar of Grenth",
    "Avatar of Lyssa",
    "Avatar of Melandru",
    "Avatar of Melandru (PvP)",
    "Balthazar's Rage",
    "Banishing Strike",
    "Banishing Strike (PvP)",
    "Chilling Victory",
    "Conviction",
    "Crippling Sweep",
    "Dust Cloak",
    "Dust Cloak (PvP)",
    "Dwayna's Touch",
    "Ebon Dust Aura",
    "Enchanted Haste",
    "Eremite's Attack",
    "Eremite's Zeal",
    "Eternal Aura",
    "Extend Enchantments",
    "Faithful Intervention",
    "Featherfoot Grace",
    "Fleeting Stability",
    "Grenth's Fingers",
    "Grenth's Grasp",
    "Guiding Hands",
    "Guiding Hands (PvP)",
    "Harrier's Grasp",
    "Harrier's Haste",
    "Heart of Fury",
    "Heart of Fury (PvP)",
    "Heart of Holy Flame",
    "Imbue Health",
    "Intimidating Aura",
    "Irresistible Sweep",
    "Irresistible Sweep (PvP)",
    "Lyssa's Assault",
    "Lyssa's Haste",
    "Lyssa's Haste (PvP)",
    "Meditation",
    "Mirage Cloak",
    "Mystic Corruption",
    "Mystic Healing",
    "Mystic Healing (PvP)",
    "Mystic Regeneration",
    "Mystic Regeneration (PvP)",
    "Mystic Sandstorm",
    "Mystic Sweep",
    "Mystic Twister",
    "Mystic Vigor",
    "Natural Healing",
    "Onslaught",
    "Onslaught (PvP)",
    "Pious Assault",
    "Pious Assault (PvP)",
    "Pious Concentration",
    "Pious Haste",
    "Pious Renewal",
    "Pious Restoration",
    "Reap Impurities",
    "Reaper's Sweep",
    "Rending Aura",
    "Rending Sweep",
    "Rending Touch",
    "Sand Shards",
    "Signet of Pious Light",
    "Staggering Force",
    "Test of Faith",
    "Twin Moon Sweep",
    "Twin Moon Sweep (PvP)",
    "Veil of Thorns",
    "Victorious Sweep",
    "Vital Boon",
    "Vow of Piety",
    "Vow of Silence",
    "Vow of Strength",
    "Watchful Intervention",
    "Wearying Strike",
    "Whirling Charge",
    "Winds of Disenchantment",
    "Wounding Strike",
    "Wounding Strike (PvP)",
    "Zealous Renewal",
    "Zealous Vow",
    "Sunspear Rebirth Signet",
    "Lightbringer Signet",
    "Lightbringer's Gaze",
  ].map(toNormalized)
);
