import { toNormalized } from "../../name-mappers";

export const prophecy_skills = new Set(
  [
    '"Fear Me!"',
    '"I Will Avenge You!"',
    '"I Will Survive!"',
    '"To the Limit!"',
    '"Victory Is Mine!"',
    "Axe Twist",
    "Backbreaker",
    "Belly Smash",
    "Bonetti's Defense",
    "Bull's Charge",
    "Crude Swing",
    "Crushing Blow",
    "Deadly Riposte",
    "Deflect Arrows",
    "Defy Pain",
    "Defy Pain (PvP)",
    "Desperation Blow",
    "Disciplined Stance",
    "Dolyak Signet",
    "Dwarven Battle Stance",
    "Earth Shaker",
    "Eviscerate",
    "Flourish",
    "Flurry",
    "Galrath Slash",
    "Gladiator's Defense",
    "Griffon's Sweep",
    "Penetrating Blow",
    "Protector's Strike",
    "Pure Strike",
    "Riposte",
    "Rush",
    "Shield Stance",
    "Skull Crack",
    "Warrior's Endurance",
    "Warrior's Endurance (PvP)",
    "Wary Stance",
    "Bestial Pounce",
    "Brutal Strike",
    "Call of Protection",
    "Crippling Shot",
    "Dodge",
    "Dryder's Defenses",
    "Dust Trap",
    "Edge of Extinction",
    "Feral Lunge",
    "Fertile Season",
    "Frozen Soil",
    "Greater Conflagration",
    "Healing Spring",
    "Ignite Arrows",
    "Incendiary Arrows",
    "Marksman's Wager",
    "Melandru's Arrows",
    "Melandru's Assault",
    "Melandru's Assault (PvP)",
    "Melandru's Resilience",
    "Muddy Terrain",
    "Oath Shot",
    "Otyugh's Cry",
    "Penetrating Attack",
    "Penetrating Attack (PvP)",
    "Point Blank Shot",
    "Poison Arrow",
    "Practiced Stance",
    "Predator's Pounce",
    "Predatory Season",
    "Punishing Shot",
    "Revive Animal",
    "Serpent's Quickness",
    "Symbiosis",
    "Symbiotic Bond",
    "Tiger's Fury",
    "Winter",
    "Upkeep",
    "Amity",
    "Aura of Faith",
    "Balthazar's Spirit",
    "Blessed Aura",
    "Contemplation of Purity",
    "Divine Healing",
    "Divine Spirit",
    "Dwayna's Kiss",
    "Essence Bond",
    "Heal Area",
    "Heal Other",
    "Healing Hands",
    "Holy Strike",
    "Holy Wrath",
    "Life Attunement",
    "Life Barrier",
    "Light of Dwayna",
    "Live Vicariously",
    "Mark of Protection",
    "Mend Condition",
    "Pacifism",
    "Peace and Harmony",
    "Protective Bond",
    "Restore Condition",
    "Restore Life",
    "Scourge Sacrifice",
    "Shield of Deflection",
    "Shield of Judgment",
    "Smite",
    "Succor",
    "Symbol of Wrath",
    "Unyielding Aura",
    "Unyielding Aura (PvP)",
    "Vengeance",
    "Vigorous Spirit",
    "Vital Blessing",
    "Watchful Spirit",
    "Sacrifice",
    "Animate Bone Horror",
    "Aura of the Lich",
    "Awaken the Blood",
    "Blood Renewal",
    "Blood Ritual",
    "Consume Corpse",
    "Dark Fury",
    "Deathly Chill",
    "Desecrate Enchantments",
    "Enfeeble",
    "Enfeeble (PvP)",
    "Feast of Corruption",
    "Infuse Condition",
    "Insidious Parasite",
    "Life Transfer",
    "Malaise",
    "Malign Intervention",
    "Mark of Subversion",
    "Necrotic Traversal",
    "Offering of Blood",
    "Order of the Vampire",
    "Plague Sending",
    "Price of Failure",
    "Shadow Strike",
    "Shadow of Fear",
    "Soul Barbs",
    "Soul Leech",
    "Spinal Shivers",
    "Spiteful Spirit",
    "Touch of Agony",
    "Vampiric Touch",
    "Verata's Aura",
    "Verata's Gaze",
    "Verata's Sacrifice",
    "Virulence",
    "Well of Power",
    "Well of Suffering",
    "Wither",
    "Arcane Thievery",
    "Blackout",
    "Channeling",
    "Chaos Storm",
    "Distortion",
    "Elemental Resistance",
    "Ether Lord",
    "Ethereal Burden",
    "Fevered Dreams",
    "Fevered Dreams (PvP)",
    "Guilt",
    "Illusion of Weakness",
    "Illusionary Weaponry",
    "Illusionary Weaponry (PvP)",
    "Ineptitude",
    "Inspired Enchantment",
    "Inspired Hex",
    "Keystone Signet",
    "Mantra of Concentration",
    "Mantra of Recall",
    "Mantra of Signets",
    "Mantra of Signets (PvP)",
    "Migraine",
    "Migraine (PvP)",
    "Panic",
    "Phantom Pain",
    "Physical Resistance",
    "Power Block",
    "Power Leak",
    "Shame",
    "Shatter Delusions",
    "Shatter Delusions (PvP)",
    "Signet of Midnight",
    "Signet of Weariness",
    "Spirit of Failure",
    "Sympathetic Visage",
    "Wastrel's Worry",
    "Armor of Frost",
    "Armor of Mist",
    "Chain Lightning",
    "Crystal Wave",
    "Earthquake",
    "Eruption",
    "Ether Prodigy",
    "Ether Renewal",
    "Ether Renewal (PvP)",
    "Flame Burst",
    "Frozen Burst",
    "Glimmering Mark",
    "Glyph of Concentration",
    "Glyph of Energy",
    "Glyph of Renewal",
    "Glyph of Sacrifice",
    "Grasping Earth",
    "Ice Prison",
    "Incendiary Bonds",
    "Iron Mist",
    "Kinetic Armor",
    "Lava Font",
    "Lightning Javelin",
    "Magnetic Aura",
    "Mark of Rodgort",
    "Meteor Shower",
    "Mind Shock",
    "Mind Shock (PvP)",
    "Mist Form",
    "Mist Form (PvP)",
    "Phoenix",
    "Rodgort's Invocation",
    "Searing Heat",
    "Shard Storm",
    "Shock",
    "Swirling Aura",
    "Thunderclap",
    "Ward Against Elements",
    "Ward Against Harm",
    "Ward Against Harm (PvP)",
    "Water Trident",
    "Whirlwind",
    "Windborne Speed",
  ].map(toNormalized)
);
