import { toNormalized } from "../../name-mappers";


export const all_pve_skills = new Set([
  // "Signet of Capture",
  "\"Together as One!\"",
  "Heroic Refrain",
  "Judgment Strike",
  "Over the Limit",
  "Seven Weapons Stance",
  "Shadow Theft",
  "Soul Taker",
  "Time Ward",
  "Vow of Revolution",
  "Weapons of Three Forges",
  "\"Save Yourselves!\"",
  "Aura of Holy Might",
  "Elemental Lord",
  "Ether Nightmare",
  "Selfless Spirit",
  "Shadow Sanctuary",
  "Signet of Corruption",
  "Spear of Fury",
  "Summon Spirits",
  "Triple Shot",
  "Lightbringer Signet",
  "Lightbringer's Gaze",
  "\"There's Nothing to Fear!\"",
  "Critical Agility",
  "Cry of Pain",
  "Eternal Aura",
  "Intensity",
  "Necrosis",
  "Never Rampage Alone",
  "Seed of Life",
  "Sunspear Rebirth Signet",
  "Vampirism",
  "Whirlwind Attack",
  "Air of Superiority",
  "Asuran Scan",
  "Mental Block",
  "Mindbender",
  "Pain Inverter",
  "Radiation Field",
  "Smooth Criminal",
  "Summon Ice Imp",
  "Summon Mursaat",
  "Summon Naga Shaman",
  "Summon Ruby Djinn",
  "Technobabble",
  "\"By Ural's Hammer!\"",
  "\"Don't Trip!\"",
  "Alkar's Alchemical Acid",
  "Black Powder Mine",
  "Brawling Headbutt",
  "Breath of the Great Dwarf",
  "Drunken Master",
  "Dwarven Stability",
  "Ear Bite",
  "Great Dwarf Armor",
  "Great Dwarf Weapon",
  "Light of Deldrimor",
  "Low Blow",
  "Snow Storm",
  "Deft Strike",
  "Ebon Battle Standard of Courage",
  "Ebon Battle Standard of Honor",
  "Ebon Battle Standard of Wisdom",
  "Ebon Escape",
  "Ebon Vanguard Assassin Support",
  "Ebon Vanguard Sniper Support",
  "Signet of Infection",
  "Sneak Attack",
  "Tryptophan Signet",
  "Weakness Trap",
  "Winds",
  "\"Dodge This!\"",
  "\"Finish Him!\"",
  "\"I Am Unstoppable!\"",
  "\"I Am the Strongest!\"",
  "\"You Are All Weaklings!\"",
  "\"You Move Like a Dwarf!\"",
  "A Touch of Guile",
  "Club of a Thousand Bears",
  "Feel No Pain",
  "Raven Blessing",
  "Ursan Blessing",
  "Volfen Blessing"
].map(toNormalized))