const pairs: { name: string; id: number }[] = [
  { name: "Fast Casting", id: 0 },
  { name: "Illusion Magic", id: 1 },
  { name: "Domination Magic", id: 2 },
  { name: "Inspiration Magic", id: 3 },
  { name: "Blood Magic", id: 4 },
  { name: "Death Magic", id: 5 },
  { name: "Soul Reaping", id: 6 },
  { name: "Curses", id: 7 },
  { name: "Air Magic", id: 8 },
  { name: "Earth Magic", id: 9 },
  { name: "Fire Magic", id: 10 },
  { name: "Water Magic", id: 11 },
  { name: "Energy Storage", id: 12 },
  { name: "Healing Prayers", id: 13 },
  { name: "Smiting Prayers", id: 14 },
  { name: "Protection Prayers", id: 15 },
  { name: "Divine Favor", id: 16 },
  { name: "Strength", id: 17 },
  { name: "Axe Mastery", id: 18 },
  { name: "Hammer Mastery", id: 19 },
  { name: "Swordsmanship", id: 20 },
  { name: "Tactics", id: 21 },
  { name: "Beast Mastery", id: 22 },
  { name: "Expertise", id: 23 },
  { name: "Wilderness Survival", id: 24 },
  { name: "Marksmanship", id: 25 },
  { name: "Dagger Mastery", id: 29 },
  { name: "Deadly Arts", id: 30 },
  { name: "Shadow Arts", id: 31 },
  { name: "Communing", id: 32 },
  { name: "Restoration Magic", id: 33 },
  { name: "Channeling Magic", id: 34 },
  { name: "Critical Strikes", id: 35 },
  { name: "Spawning Power", id: 36 },
  { name: "Spear Mastery", id: 37 },
  { name: "Command", id: 38 },
  { name: "Motivation", id: 39 },
  { name: "Leadership", id: 40 },
  { name: "Scythe Mastery", id: 41 },
  { name: "Wind Prayers", id: 42 },
  { name: "Earth Prayers", id: 43 },
  { name: "Mysticism", id: 44 },
].map((o) => ({
  name: String(o.name).toLocaleLowerCase().replaceAll(" ", "-"),
  id: o.id,
}));

export const attribute_name_to_id = new Map(pairs.map((o) => [o.name, o.id]));
export const attribute_id_to_name = new Map(pairs.map((o) => [o.id, o.name]));
