import { toNormalized } from "../name-mappers";

const restoration_magic = [
  "Blind Was Mingson",
  "Death Pact Signet",
  "Death Pact Signet (PvP)",
  "Defiant Was Xinrae",
  "Flesh of My Flesh",
  "Flesh of My Flesh (PvP)",
  "Generous Was Tsungrai",
  "Ghostmirror Light",
  "Life",
  "Life (PvP)",
  "Lively Was Naomei",
  "Mend Body and Soul",
  "Mend Body and Soul (Togo)",
  "Mending Grip",
  "Preservation",
  "Preservation (PvP)",
  "Protective Was Kaolai",
  "Pure Was Li Ming",
  "Recovery",
  "Recovery (PvP)",
  "Recuperation",
  "Recuperation (PvP)",
  "Rejuvenation",
  "Rejuvenation (PvP)",
  "Resilient Was Xiko",
  "Resilient Weapon",
  "Soothing Memories",
  "Spirit Light",
  "Spirit Light Weapon",
  "Spirit Transfer",
  "Spiritleech Aura",
  "Tranquil Was Tanasen",
  "Vengeful Was Khanhei",
  "Vengeful Weapon",
  "Vocal Was Sogolon",
  "Weapon of Remedy",
  "Weapon of Shadow",
  "Weapon of Warding",
  "Weapon of Warding (PvP)",
  "Wielder's Boon",
  "Xinrae's Weapon",
].map(toNormalized);

const healing_prayers = [
  "Cure Hex",
  "Dwayna's Kiss",
  "Dwayna's Sorrow",
  "Ethereal Light",
  "Gift of Health",
  "Glimmer of Light",
  "Heal Area",
  "Heal Other",
  "Heal Party",
  "Heal Party (PvP)",
  "Healer's Covenant",
  "Healing Breeze",
  "Healing Burst",
  "Healing Hands",
  "Healing Light",
  "Healing Ribbon",
  "Healing Ring",
  "Healing Seed",
  "Healing Touch",
  "Healing Whisper",
  "Infuse Health",
  "Jamei's Gaze",
  "Karei's Healing Circle",
  "Light of Deliverance",
  "Light of Deliverance (PvP)",
  "Live Vicariously",
  "Mending",
  "Orison of Healing",
  "Patient Spirit",
  "Renew Life",
  "Restful Breeze",
  "Restore Life",
  "Resurrection Chant",
  "Signet of Rejuvenation",
  "Spotless Mind",
  "Spotless Soul",
  "Supportive Spirit",
  "Vigorous Spirit",
  "Word of Healing",
  "Words of Comfort",
  "Boon Signet",
  "Gift of Health",
  "Healer's Boon",
  "Healer's Covenant",
  "Holy Haste",
].map(toNormalized);

const regen_skills = [
  "Other",
  '"I Will Avenge You!"',
  '"I Will Survive!"',
  '"Never Surrender!"',
  '"Never Surrender!" (PvP)',
  "Any",
  '"Together as One!"',
  "Blood Renewal",
  "Celestial Stance",
  "Conviction",
  "Cry of Madness",
  "Any",
  "Feel No Pain",
  "Any",
  "Feigned Neutrality",
].map(toNormalized);

export const all_heal_skills = new Set(
  [
    '"There\'s Nothing to Fear!"',
    "Air of Superiority",
    "Angelic Bond",
    "Angelic Protection",
    "Aura of Restoration",
    "Aura of Restoration (PvP)",
    "Avatar of Dwayna",
    "Avatar of Dwayna (PvP)",
    "Blessed Light",
    "Blood Bond",
    "Blood of the Master",
    "Boon Signet",
    "Boon of Creation",
    "Breath of the Great Dwarf",
    "Chorus of Restoration",
    "Comfort Animal",
    "Comfort Animal (PvP)",
    "Companionship",
    "Cure Hex",
    "Death's Charge",
    "Dismiss Condition",
    "Divine Boon",
    "Divine Healing",
    "Divine Intervention",
    "Dwayna's Kiss",
    "Dwayna's Sorrow",
    "Dwayna's Touch",
    "Ebon Escape",
    "Elemental Lord",
    "Empathic Removal",
    "Ether Feast",
    "Ether Renewal",
    "Ether Renewal (PvP)",
    "Ethereal Light",
    "Extinguish",
    "Faithful Intervention",
    "Feast for the Dead",
    "Feast of Souls",
    "Finale of Restoration",
    "Finale of Restoration (PvP)",
    "Foul Feast",
    "Ghostmirror Light",
    "Gift of Health",
    "Glimmer of Light",
    "Glyph of Restoration",
    "Heal Area",
    "Heal Other",
    "Heal Party",
    "Heal Party (PvP)",
    "Heal as One",
    "Heal as One (PvP)",
    "Healing Burst",
    "Healing Light",
    "Healing Ribbon",
    "Healing Ring",
    "Healing Signet",
    "Healing Spring",
    "Healing Touch",
    "Healing Whisper",
    "Heart of Shadow",
    "Heaven's Delight",
    "Illusion of Weakness",
    "Imbue Health",
    "Infuse Health",
    "Jamei's Gaze",
    "Karei's Healing Circle",
    "Leader's Comfort",
    "Life",
    "Life (PvP)",
    "Life Sheath",
    "Light of Deliverance",
    "Light of Deliverance (PvP)",
    "Lion's Comfort",
    "Mantra of Signets",
    "Mantra of Signets (PvP)",
    "Mark of Protection",
    "Mend Ailment",
    "Mend Body and Soul",
    "Mend Condition",
    "Mending Touch",
    "Mist Form",
    "Mist Form (PvP)",
    "Mystic Healing",
    "Mystic Healing (PvP)",
    "Natural Healing",
    "Orison of Healing",
    "Parasitic Bond",
    "Patient Spirit",
    "Phoenix",
    "Predatory Bond",
    "Predatory Bond (PvP)",
    "Preservation",
    "Preservation (PvP)",
    "Protective Was Kaolai",
    "Rejuvenation",
    "Rejuvenation (PvP)",
    "Release Enchantments",
    "Renew Life",
    "Restore Condition",
    "Reversal of Fortune",
    "Seed of Life",
    "Shadow Refuge",
    "Shield Guardian",
    "Shielding Hands",
  ]
    .map(toNormalized)
    .concat(regen_skills)
    .concat(restoration_magic)
    .concat(healing_prayers)
);
