import { toNormalized } from "../name-mappers";

const strength_skills = [
  "Body Blow",
  "Bull's Charge",
  "Bull's Strike",
  "Burst of Aggression",
  "Charging Strike",
  "Counterattack",
  "Defy Pain",
  "Defy Pain (PvP)",
  "Disarm",
  "Dolyak Signet",
  "Dwarven Battle Stance",
  "Endure Pain",
  "Enraging Charge",
  "Flail",
  "Flourish",
  "Griffon's Sweep",
  "Headbutt",
  "Leviathan's Sweep",
  "Lion's Comfort",
  "Magehunter Strike",
  "Power Attack",
  "Primal Rage",
  "Protector's Strike",
  "Rage of the Ntouka",
  "Rush",
  "Seven Weapons Stance",
  "Shield Bash",
  "Signet of Stamina",
  "Signet of Strength",
  "Sprint",
  "Tiger Stance",
  "Warrior's Cunning",
  "Warrior's Endurance",
  "Warrior's Endurance (PvP)",
].map(toNormalized);

const expertise_skills = [
  "\"Together as One!\"",
  "Archer's Signet",
  "Distracting Shot",
  "Dodge",
  "Escape",
  "Escape (PvP)",
  "Expert Focus",
  "Expert's Dexterity",
  "Expert's Dexterity (PvP)",
  "Glass Arrows",
  "Glass Arrows (PvP)",
  "Infuriating Heat",
  "Lightning Reflexes",
  "Lightning Reflexes (PvP)",
  "Marksman's Wager",
  "Oath Shot",
  "Point Blank Shot",
  "Practiced Stance",
  "Throw Dirt",
  "Trapper's Focus",
  "Trapper's Speed",
  "Whirling Defense",
  "Zojun's Haste",
  "Zojun's Shot",
].map(toNormalized);

const divine_favor_skills = [
  "Blessed Aura",
  "Blessed Light",
  "Blessed Signet",
  "Boon Signet",
  "Contemplation of Purity",
  "Deny Hexes",
  "Divine Boon",
  "Divine Healing",
  "Divine Intervention",
  "Divine Spirit",
  "Healer's Boon",
  "Heaven's Delight",
  "Holy Haste",
  "Judgment Strike",
  "Peace and Harmony",
  "Release Enchantments",
  "Scribe's Insight",
  "Signet of Devotion",
  "Smiter's Boon",
  "Smiter's Boon (PvP)",
  "Spell Breaker",
  "Spell Shield",
  "Unyielding Aura",
  "Unyielding Aura (PvP)",
  "Watchful Healing",
  "Watchful Spirit",
  "Withdraw Hexes",
].map(toNormalized);

const soul_reaping_skills = [
  "Angorodon's Gaze",
  "Foul Feast",
  "Hexer's Vigor",
  "Icy Veins",
  "Masochism",
  "Masochism (PvP)",
  "Reaper's Mark",
  "Signet of Lost Souls",
  "Signet of Sorrow",
  "Soul Taker",
  "Wail of Doom",
].map(toNormalized);

const fast_casting_skills = [
  "Arcane Languor",
  "Keystone Signet",
  "Mantra of Recovery",
  "Persistence of Memory",
  "Power Return",
  "Psychic Instability",
  "Psychic Instability (PvP)",
  "Stolen Speed",
  "Stolen Speed (PvP)",
  "Symbolic Celerity",
  "Symbolic Posture",
  "Symbols of Inspiration",
  "Time Ward",
].map(toNormalized)

const energy_storage_skills = [
  "Aura of Restoration",
  "Aura of Restoration (PvP)",
  "Elemental Attunement",
  "Energy Blast",
  "Energy Boon",
  "Ether Prism",
  "Ether Prodigy",
  "Ether Renewal",
  "Ether Renewal (PvP)",
  "Glyph of Energy",
  "Glyph of Lesser Energy",
  "Glyph of Restoration",
  "Master of Magic",
  "Over the Limit",
].map(toNormalized);

const critical_strikes_skills = [
  "Assassin's Remedy",
  "Assassin's Remedy (PvP)",
  "Black Lotus Strike",
  "Critical Defenses",
  "Critical Eye",
  "Critical Strike",
  "Dark Apostasy",
  "Deadly Haste",
  "Locust's Fury",
  "Malicious Strike",
  "Palm Strike",
  "Seeping Wound",
  "Shadow Theft",
  "Sharpen Daggers",
  "Shattering Assault",
  "Twisting Fangs",
  "Unsuspecting Strike",
  "Way of the Assassin",
  "Way of the Master",
].map(toNormalized);

const spawning_power_skills = [
  "Anguished Was Lingwah",
  "Attuned Was Songkai",
  "Boon of Creation",
  "Consume Soul",
  "Doom",
  "Empowerment",
  "Empowerment (PvP)",
  "Energetic Was Lee Sa",
  "Explosive Growth",
  "Feast of Souls",
  "Ghostly Haste",
  "Reclaim Essence",
  "Renewing Memories",
  "Ritual Lord",
  "Rupture Soul",
  "Sight Beyond Sight",
  "Signet of Binding",
  "Signet of Creation",
  "Soul Twisting",
  "Spirit Channeling",
  "Spirit to Flesh",
  "Spirit's Gift",
  "Spirit's Strength",
  "Weapon of Renewal",
  "Weapons of Three Forges",
  "Wielder's Remedy",
  "Wielder's Zeal",
].map(toNormalized);

const leadership_skills = [
  "\"Lead the Way!\"",
  "\"Make Your Time!\"",
  "\"They're on Fire!\"",
  "Aggressive Refrain",
  "Angelic Bond",
  "Angelic Protection",
  "Anthem of Flame",
  "Anthem of Fury",
  "Awe",
  "Blazing Finale",
  "Blazing Finale (PvP)",
  "Burning Refrain",
  "Burning Shield",
  "Defensive Anthem",
  "Defensive Anthem (PvP)",
  "Enduring Harmony",
  "Focused Anger",
  "Glowing Signet",
  "Hasty Refrain",
  "Heroic Refrain",
  "Leader's Comfort",
  "Natural Temper",
  "Signet of Return",
  "Signet of Return (PvP)",
  "Soldier's Fury",
  "Spear Swipe",
].map(toNormalized);

const mysticism_skills = [
  "Arcane Zeal",
  "Aura Slicer",
  "Avatar of Balthazar",
  "Avatar of Dwayna",
  "Avatar of Dwayna (PvP)",
  "Avatar of Grenth",
  "Avatar of Lyssa",
  "Avatar of Melandru",
  "Avatar of Melandru (PvP)",
  "Balthazar's Rage",
  "Banishing Strike",
  "Banishing Strike (PvP)",
  "Eremite's Zeal",
  "Extend Enchantments",
  "Faithful Intervention",
  "Heart of Fury",
  "Heart of Fury (PvP)",
  "Heart of Holy Flame",
  "Imbue Health",
  "Intimidating Aura",
  "Meditation",
  "Mystic Corruption",
  "Mystic Sweep",
  "Mystic Vigor",
  "Pious Fury",
  "Pious Fury (PvP)",
  "Pious Haste",
  "Pious Renewal",
  "Rending Touch",
  "Vow of Revolution",
  "Vow of Silence",
  "Watchful Intervention",
  "Zealous Renewal",
].map(toNormalized)

export const all_primary_attribute_skills = new Set([
  ...strength_skills,
  ...expertise_skills,
  ...divine_favor_skills,
  ...soul_reaping_skills,
  ...fast_casting_skills,
  ...energy_storage_skills,
  ...critical_strikes_skills,
  ...spawning_power_skills,
  ...leadership_skills,
  ...mysticism_skills
])