import { toNormalized } from "../name-mappers";

export const self_heals = new Set(
  [
    "Healing Signet",
    "Lion's Comfort",
    "Troll Unguent",
    "Heal as One",
    "Melandru's Resilience",
    "Contemplation of Purity",
    "Empathic Removal",
    "Necromancer",
    "Blood Renewal",
    "Hexer's Vigor",
    "Parasitic Bond",
    "Signet of Lost Souls",
    "Soul Feast",
    "Taste of Death",
    "Taste of Pain",
    "Drain Enchantment",
    "Ether Feast",
    "Mantra of Signets",
    "Illusion of Weakness",
    "Aura of Restoration",
    "Elemental Lord",
    "Ether Renewal",
    "Glyph of Restoration",
    "Mist Form",
    "Swirling Aura",
    "Death's Charge",
    "Death's Retreat",
    "Heart of Shadow",
    "Shadow Refuge",
    "Shadow Sanctuary",
    "Shroud of Distress",
    "Feigned Neutrality",
    "Caretaker's Charge",
    "Boon of Creation",
    "Generous Was Tsungrai",
    '"Help Me!"',
    "Leader's Comfort",
    "Signet of Synergy",
    "Avatar of Dwayna",
    "Conviction",
    "Dwayna's Touch",
    "Faithful Intervention",
    "Mystic Healing",
    "Mystic Regeneration",
    "Mystic Vigor",
    "Natural Healing",
    "Pious Renewal",
    "Pious Restoration",
    "Signet of Pious Light",
    "Twin Moon Sweep",
    "Victorious Sweep",
    "Vital Boon",
    "Watchful Intervention",
    "Ebon Escape",
    "Junundu Bite",
    "Junundu Wail",
    "Siege Devourer Feast",
  ].map(toNormalized)
);
