import { toNormalized } from "../../name-mappers";

export const all_air_skills = new Set(
  [
    "Air Attunement",
    "Arc Lightning",
    "Blinding Flash",
    "Blinding Surge",
    "Chain Lightning",
    "Chilling Winds",
    "Conjure Lightning",
    "Enervating Charge",
    "Gale",
    "Glimmering Mark",
    "Glyph of Swiftness",
    "Gust",
    "Invoke Lightning",
    "Lightning Bolt",
    "Lightning Hammer",
    "Lightning Hammer (PvP)",
    "Lightning Javelin",
    "Lightning Orb",
    "Lightning Strike",
    "Lightning Surge",
    "Lightning Touch",
    "Mind Shock",
    "Mind Shock (PvP)",
    "Ride the Lightning",
    "Ride the Lightning (PvP)",
    "Shell Shock",
    "Shock",
    "Shock Arrow",
    "Storm Djinn's Haste",
    "Teinai's Wind",
    "Thunderclap",
    "Whirlwind",
    "Windborne Speed",
  ].map(toNormalized)
);
