import { toNormalized } from "../../name-mappers";

export const all_earth_skills = new Set(
  [
    "Aftershock",
    "Armor of Earth",
    "Ash Blast",
    "Churning Earth",
    "Crystal Wave",
    "Dragon's Stomp",
    "Earth Attunement",
    "Earthen Shackles",
    "Earthquake",
    "Ebon Hawk",
    "Eruption",
    "Glowstone",
    "Grasping Earth",
    "Iron Mist",
    "Kinetic Armor",
    "Magnetic Aura",
    "Magnetic Surge",
    "Obsidian Flame",
    "Obsidian Flame (PvP)",
    "Obsidian Flesh",
    "Sandstorm",
    "Shockwave",
    "Sliver Armor",
    "Stone Daggers",
    "Stone Sheath",
    "Stone Striker",
    "Stoneflesh Aura",
    "Stoning",
    "Teinai's Crystals",
    "Unsteady Ground",
    "Ward Against Elements",
    "Ward Against Foes",
    "Ward Against Melee",
    "Ward of Stability",
    "Ward of Weakness",
  ].map(toNormalized)
);
