import { toNormalized } from "../../name-mappers";

export const all_fire_skills = new Set(
  [
    "Bed of Coals",
    "Breath of Fire",
    "Burning Speed",
    "Conjure Flame",
    "Double Dragon",
    "Elemental Flame",
    "Elemental Flame (PvP)",
    "Fire Attunement",
    "Fire Storm",
    "Fireball",
    "Flame Burst",
    "Flame Djinn's Haste",
    "Flare",
    "Glowing Gaze",
    "Glyph of Immolation",
    "Immolate",
    "Incendiary Bonds",
    "Inferno",
    "Lava Arrows",
    "Lava Font",
    "Liquid Flame",
    "Mark of Rodgort",
    "Meteor",
    "Meteor Shower",
    "Mind Blast",
    "Mind Burn",
    "Phoenix",
    "Rodgort's Invocation",
    "Savannah Heat",
    "Savannah Heat (PvP)",
    "Searing Flames",
    "Searing Heat",
    "Smoldering Embers",
    "Star Burst",
    "Teinai's Heat",
  ].map(toNormalized)
);
