import { toNormalized } from "../../name-mappers";

export const all_water_skills = new Set(
  [
    "Armor of Frost",
    "Armor of Mist",
    "Blurred Vision",
    "Conjure Frost",
    "Deep Freeze",
    "Freezing Gust",
    "Frigid Armor",
    "Frozen Burst",
    "Glowing Ice",
    "Ice Prison",
    "Ice Spear",
    "Ice Spikes",
    "Icy Prism",
    "Icy Shackles",
    "Maelstrom",
    "Mind Freeze",
    "Mind Freeze (PvP)",
    "Mirror of Ice",
    "Mist Form",
    "Mist Form (PvP)",
    "Rust",
    "Shard Storm",
    "Shatterstone",
    "Slippery Ground",
    "Slippery Ground (PvP)",
    "Steam",
    "Swirling Aura",
    "Teinai's Prison",
    "Vapor Blade",
    "Ward Against Harm",
    "Ward Against Harm (PvP)",
    "Water Attunement",
    "Water Trident",
    "Winter's Embrace",
  ].map(toNormalized)
);
